### PR TITLE
added tip 4 in template - verified code

### PR DESCRIPTION
**Pull request by aquaomarine**
issue #6 

- [x] Added timeout on line 41 so code could run & pass
- [x] Intro Content needs to be added
- [x] Summary Content needs to be added

### CODE REVIEW

**Review by discombobulateme — COMMENTED** [review]
@aquaomarine same here: after checking the tip, can you write the summary? if you are unsure, maybe you can write a paragraph about it and send it to Diego?
Anyway: WELL DONE!!!! Really amazing job getting things done <3

**Comment by aquaomarine** [comment]
> @aquaomarine same here: after checking the tip, can you write the summary? if you are unsure, maybe you can write a paragraph about it and send it to Diego?
> Anyway: WELL DONE!!!! Really amazing job getting things done <3

I believe @janackeh will be adding content!

**Review by Roseywinter — APPROVED** [review]
Updated Intro and Summary content.

**Review by janackeh — APPROVED** [review]
Updated/edited content

**Pull request merged**
