### PR TITLE
Resource Page

### PR DESCRIPTION
**Pull request by aquaomarine**
Issue #378 

Iteration 1:
- [x] Themes from current iteration will be added (footer/navbar)
- [x] Text from Figma will be added 
- [x] Links Will be added using Flexbox
1. Images also need to be added

Iteration 2:

- [ ] Navbar will be reflected as in the design
- [ ] Menu will be reflected as in the design
- [ ] Styling will better reflect Figma Design 

Image

### CODE REVIEW

**Comment by aquaomarine** [comment]
image

**Comment by aquaomarine** [comment]
Screenshot 2023-04-18 at 6 56 14 PM

**Review by discombobulateme — DISMISSED** [review]
Hi :)

- Structurally, its missing the paragraphs underneath each item
- Stylewise images are distorted 

Yeeyyyy awesome to see the page linked from the menu :)

**Comment by aquaomarine** [comment]
Changes completed, but to note this PR isn't for styling!!!

**Review by Roseywinter — APPROVED** [review]
- External Resources header, subtitle, and sentence seem to be center aligned, rather than left aligned (as previewed in the figma).
- Test size seems oddly proportioned compared to browser (have to scroll side to side in order to read everything).
- Image re-sizing seems warped, and stretched too much height-wise.

**Other than styling issues above, all elements present and accounted for as placeholder. Approved for merge.**

**Comment by aquaomarine** [comment]
Screenshot 2023-04-24 at 3 59 00 PM
@discombobulateme

**Pull request merged**
