### PR TITLE
Tips page

### PR DESCRIPTION
**Pull request by aquaomarine**
- [x] new route http://localhost:3000/tips
- [x] made changes to the design following the mockup
- [x] adding filters

### CODE REVIEW

**Review by Roseywinter — DISMISSED** [review]

**Comment by aquaomarine** [comment]
Screenshot 2023-03-21 at 9 19 37 PM

**Comment by aquaomarine** [comment]
Screenshot 2023-03-22 at 2 50 53 PM

**Review by janackeh — APPROVED** [review]

**Comment by Roseywinter** [comment]
It says branch has merge conflicts?

**Review by Roseywinter — CHANGES_REQUESTED** [review]
Git is saying the branch has merge conflicts

**Review by Roseywinter — APPROVED** [review]

**Pull request merged**
