### PR TITLE
Tip16 JavaScript code snippets deprecated

### PR DESCRIPTION
**Pull request by janackeh**
- Updated content to match new content template
- Tested JavaScript tip several times, getting errors/tests fail, code snippet may need to be updated
- Errors I got :  1) Screenshot
       "before each" hook for "on failure":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. 

  2) Screenshot "after each" hook for "on failure": TypeError: Cannot read properties of undefined (reading 'takeScreenshot')

### CODE REVIEW

**Comment by aquaomarine** [comment]
Add a timeout before line 38 in non-updated-tips.

`beforeEach(async function() {
    this.timeout(60000)
    driver = await new Builder().forBrowser("chrome").build();
  });`

 This will ensure the driver has enough time and the test will fail and a screenshot will be taken in the current directory.
Screenshot 2023-03-10 at 1 31 35 PM

**Comment by janackeh** [comment]
Thank you @aquaomarine!!!

**Review by Roseywinter — APPROVED** [review]
Made some minor edits. Looks like it's good to merge.

**Comment by janackeh** [comment]
closing pull request - this file has been transferred to #194 - I created this one under unupdated tips instead of updated. #194 was created correctly under updated tips.

**Pull request closed without merging**
