### PR TITLE
Update Ruby Frontmatter Tips 33-48

### PR DESCRIPTION
**Pull request by janackeh**
Tip 39 - Updated Ruby frontmatter including title, sidebar label and text, removed slug

### CODE REVIEW

**Comment by janackeh** [comment]
updated Ruby Frontmatter Tip 33-48

**Comment by aquaomarine** [comment]
The title just needs to be replaced with the tips actual title. So for example tip title for tip 36 would be `title: '36: Where to Look for Selenium Information'` the sidebar title is the language now instead of the title.

**Comment by janackeh** [comment]
ok...i have to change all of them

**Comment by janackeh** [comment]
Question - is the language added to the end of the title at all or is it just the title?

**Comment by aquaomarine** [comment]
> Question - is the language added to the end of the title at all or is it just the title?

it will end with the id, which has the language at the end :)

**Review by Roseywinter — APPROVED** [review]

**Pull request merged**
