### PR TITLE
tip 5 javascript code validated and in template

### PR DESCRIPTION
**Pull request by aquaomarine**
issue #6 

- [x] added proper route for driver.get in second example
- [x] use case needs content
- [x] summary may? need content

### CODE REVIEW

**Review by discombobulateme — COMMENTED** [review]
@aquaomarine just a question: why line 25 says content need updating? were you unable to verify it? why? if not, is it something diego can or something a user, at somepoint, would do? Or... is this secrion irrelevant for the tip? I am thinking about which message are we sending to users without content, receiving this tip

**Comment by aquaomarine** [comment]
> @aquaomarine just a question: why line 25 says content need updating? were you unable to verify it? why? if not, is it something diego can or something a user, at somepoint, would do? Or... is this secrion irrelevant for the tip? I am thinking about which message are we sending to users without content, receiving this tip

I believe @janackeh will be adding content!

**Comment by aquaomarine** [comment]
Added missing content, just need a final review!

**Review by Roseywinter — APPROVED** [review]
Added content looks good

**Review by janackeh — APPROVED** [review]
Updated and edited content

**Pull request merged**
