### PR TITLE
Css design system - Dropdown

### PR DESCRIPTION
**Pull request by aquaomarine**
- [x] added dropdown vectors
- [x] added hover coloring css
- [x] added dropdown focus to show selected element in dropdown
- [x] added colors in custom.css
- [x] added text in custom.css

tested modules for animation:

- [ ] dropdown animation still in progress
    -their needs to be a checkbox functionality within the button or checkbox designed as a button so whenChecked:
     a transition happens

### CODE REVIEW

**Review by discombobulateme — APPROVED** [review]
Yeyyy its so good to see it looking like more like the design <3
In the console inspector it shows you are having issues with the dropdown. Try not to send a PR with issues. 
I believe this happened as you were working in more than one issue at a time. 
Send smaller PRs :) 
I believe there's still a lot to be implemented in the design system, so please don't close the issue.

**Comment by aquaomarine** [comment]
Screenshot 2023-04-05 at 9 24 17 AM

**Comment by discombobulateme** [comment]
@aquaomarine Please break down this issue into another issue. 
The design system is one thing, and dropdown is another :) 
Then you can get rid of this issue. But I believe there's still a difference between what's on Figma and how it is displaying... can you please leave the dropdown to another issue and recheck how the design system is being displayed?

**Comment by aquaomarine** [comment]
> @aquaomarine Please break down this issue into another issue.

Can we just move forward with this PR and keep that in mind for further requests? This is not the final dropdown, this is just to show progress.

**Pull request merged**
