### PR TITLE
tip 3 javascript, code edit(verified run) in template

### PR DESCRIPTION
**Pull request by aquaomarine**
issue #6 
- [x] added timeout line 41
- [x] added unclear await driver.get that was a comment
- [x] intro needs to be added
- [x] summary needs to be edited

### CODE REVIEW

**Review by discombobulateme — COMMENTED** [review]
Hey @aquaomarine same question for this PR, why part of the content still need update? It wouls be better to talk to Diego and, as it seem quite simple, just add waht is missing and have a beautiful updated tip done :) if possible... please make sure to have some sort of control over what still needs review to pass it over to Diego :)

**Comment by aquaomarine** [comment]
> Hey @aquaomarine same question for this PR, why part of the content still need update? It wouls be better to talk to Diego and, as it seem quite simple, just add waht is missing and have a beautiful updated tip done :) if possible... please make sure to have some sort of control over what still needs review to pass it over to Diego :)

I believe @janackeh will be adding content!

**Review by Roseywinter — APPROVED** [review]
Added intro and summary. Made some minor verbiage changes.

**Review by janackeh — APPROVED** [review]
content looks good

**Pull request merged**
