### PR TITLE
Adding tip 3 markdown file for ruby

### PR DESCRIPTION
**Pull request by Roseywinter**
Adding tip 3 markdown file for ruby. Code was checked (note made on which code could not be verified). Content validation still needed for copy.

### CODE REVIEW

**Comment by Roseywinter** [comment]
Assigned @janackeh to validate copy content.

**Comment by aquaomarine** [comment]
Approved, tip 3 is in a markdown file

**Review by aquaomarine — COMMENTED** [review]
reviewed/approved tip 3 added in .md file

**Review by discombobulateme — COMMENTED** [review]
Ohhh how awesome it is to have an updated content??? <3
Just a question. What does the tag: ==**`!! CONTENT ADDED !! --> means?

**Comment by janackeh** [comment]
I added that when I updated the content but I realize its not needed

**Comment by Roseywinter** [comment]
> Ohhh how awesome it is to have an updated content??? <3 Just a question. What does the tag: ==**`!! CONTENT ADDED !! --> means?

This is a comment added by @janackeh after she adds the updated content. I don't think we need this comment within the markdown file itself though.

**Review by janackeh — APPROVED** [review]

**Review by discombobulateme — CHANGES_REQUESTED** [review]
Tags are still showing on line 17, 58 & 142

**Comment by Roseywinter** [comment]
> I added that when I updated the content but I realize its not needed

It's ok, I just deleted them & committed to the branch.

**Review by discombobulateme — APPROVED** [review]

**Pull request merged**
